In [135]:
import pandas as pd 
import numpy as np
import re

In [136]:
# read data from excel
df = pd.read_excel('data_2.xlsx')

# print the first 5 rows
df.head()

,Deal ID,Company ID,Company Name,Description,Investor ID,Investor Name,Investor Website,Investor Status,Primary Investor Type,Other Investor Types,...,Valuation/Cash Flow,Deal Status,Primary Industry Sector,Primary Industry Group,Primary Industry Code,Verticals,All Industries,Business Status,Financing Status,PitchBook Link
0,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,10768-06,BlackRock,www.blackrock.com,Active Investor,Asset Manager,"Fund of Funds, Hedge Fund, Impact Investing, I...",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
1,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,58004-02,Bpifrance,www.bpifrance.fr,Active Investor,Sovereign Wealth Fund,"Accelerator/Incubator, Fund of Funds, Growth/E...",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
2,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,187980-13,Cathay Innovation,www.cathayinnovation.com,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
3,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,523414-99,Delphi Ventures,delphiventures.io,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
4,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,11180-08,Eurazeo,www.eurazeo.com,Active Investor,PE/Buyout,"Growth/Expansion, Infrastructure, Venture Capital",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21446 entries, 0 to 21445
Data columns (total 62 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Deal ID                                     21446 non-null  object
 1   Company ID                                  21446 non-null  object
 2   Company Name                                21446 non-null  object
 3   Description                                 21446 non-null  object
 4   Investor ID                                 21446 non-null  object
 5   Investor Name                               21446 non-null  object
 6   Investor Website                            17504 non-null  object
 7   Investor Status                             21446 non-null  object
 8   Primary Investor Type                       21446 non-null  object
 9   Other Investor Types                        10908 non-null  object
 10  Preferred Industries                        18685 non-null  object
 11  Preferred Verticals                         17358 non-null  object
 12  Investor HQ                                 19922 non-null  object
 13  Investor AUM (million, USD)                 9382 non-null   float64
 14  Lead Partner                                6436 non-null   object
 15  Lead Partner Email                          3566 non-null   object
 16  Lead Partner Phone                          3221 non-null   object
 17  Lead/Sole                                   21446 non-null  object
 18  Fund(s) Used                                4301 non-null   object
 19  Deal No.                                    21446 non-null  int64
 20  Deal Date                                   21446 non-null  datetime64[ns]
 21  Total Deal Size (million, USD)              19827 non-null  float64
 22  Deal Size Status                            19827 non-null  object
 23  Investment Size (million, USD)              4435 non-null   float64
 24  Deal Type 1                                 21446 non-null  object
 25  Deal Type 2                                 7604 non-null   object
 26  Deal Type 3                                 0 non-null      float64
 27  Deal Class                                  21446 non-null  object
 28  Debts                                       4813 non-null   object
 29  Company City                                21303 non-null  object
 30  Company State/Province                      67 non-null     object
 31  Company Post Code                           21203 non-null  object
 32  Company Country/Territory                   21446 non-null  object
 33  Company Pre-money Valuation (million, USD)  13680 non-null  float64
 34  Company Post Valuation (million, USD)       13719 non-null  float64
 35  Company Post Valuation Status               13719 non-null  object
 36  Revenue (million, USD)                      3898 non-null   float64
 37  Revenue Status                              3845 non-null   object
 38  Revenue Growth since last deal              1752 non-null   float64
 39  Gross Profit (million, USD)                 209 non-null    float64
 40  Gross Profit Status                         209 non-null    object
 41  Net Income (million, USD)                   2696 non-null   float64
 42  Net Income Status                           2696 non-null   object
 43  EBITDA (million, USD)                       2308 non-null   float64
 44  EBITDA Status                               2308 non-null   object
 45  Debt/Equity                                 1418 non-null   float64
 46  Debt/EBITDA                                 615 non-null    float64
 47  Deal Size/EBITDA                            2204 non-null   float64
 48  Valuation/EBITDA                            1532 non-null   float64
 49  Deal Size/Revenue                           3690 non-null   float64
 50  Valuation/Revenue                           2594 non-null   float64
 51  Deal Size/Cash Flow                         102 non-null    float64
 52  Valuation/Cash Flow                         44 non-null     float64
 53  Deal Status                                 21446 non-null  object
 54  Primary Industry Sector                     21446 non-null  object
 55  Primary Industry Group                      21446 non-null  object
 56  Primary Industry Code                       21446 non-null  object
 57  Verticals                                   19995 non-null  object
 58  All Industries                              21446 non-null  object
 59  Business Status                             21446 non-null  object
 60  Financing Status                            21437 non-null  object
 61  PitchBook Link                              0 non-null      float64
dtypes: datetime64[ns](1), float64(20), int64(1), object(40)
memory usage: 10.1+ MB

In [138]:
# # Build the regex dynamically
# ignore_pattern = '|'.join(['Private\s+Equity', 'Financial\s+Services', 'Electrical\s+Equipment'])
# pattern = rf'\((?:[A-Z]{2,4}:\s*[A-Z0-9.]+)\)|\((?![A-Z]{2,4}:\s*[A-Z0-9.]+)(?!{ignore_pattern})([A-Za-zÀ-ÖØ-öø-ÿ-]+(?:\s+[A-Za-zÀ-ÖØ-öø-ÿ-]+)+)\)'

# # Compile regex for better performance
# compiled_regex = re.compile(pattern)

In [139]:
# # Select the columns investors
# investors = df['Investors']

# # Function to extract partner names
# def extract_partners(text):
#     matches = re.findall(pattern, text)
#     # Flatten the list and remove empty strings
#     cleaned_matches = [match for sublist in matches for match in sublist if match]
#     return ", ".join(cleaned_matches) if cleaned_matches else None
    

# # Apply function to create 'partners' column only to the first 5 rows
# df["Partners"] = investors.apply(extract_partners)

In [140]:
from collections import Counter

# Function to filter two-word names
def get_two_word_names(partners_list):
    two_word_names = []
    for names in partners_list:
        if names:  # Ensure it's not None
            for name in names.split(", "):  # Handle multiple names
                if len(name.split()) == 2:  # Check if it has exactly two words
                    two_word_names.append(name)
    return two_word_names

# Extract all partner names from the column
all_partners = df["Lead Partner"].dropna().tolist()

# Get only two-word names
two_word_names = get_two_word_names(all_partners)

# Count occurrences
name_counts = Counter(two_word_names)

# Convert to DataFrame for visualization
df_name_counts = pd.DataFrame(name_counts.items(), columns=["Two-Word Name", "Frequency"]).sort_values(by="Frequency", ascending=False)

# Display the frequency table
df_name_counts.head(50)

                Two-Word Name  Frequency
397               Xavier Niel         81
237           Thibaud Elziere         39
858           Joséphine Marie         30
2075          Guillaume Aubin         24
1153           Romain Lavault         22
787    Jean-David Chamboredon         21
59             Thierry Laugel         19
1940  Jacques-Antoine Granjon         19
424        Stéphanie Hospital         19
242           Renaud Guillerm         18
1345            Chahra Louafi         17
2841          Jérémie Berrebi         16
2148          Dominique Vidal         16
276                Celia Hart         16
760          Vincent Deltrieu         16
293         Antoine Papiernik         15
81              Jérôme Guéret         15
50        Clémentine Cazenave         15
1823       Philippe Collombel         15
162             Alison Imbert         14
315            Antoine Freysz         14
2149           Marc Simoncini         14
295        Samantha Jérusalmy         14
652            Xavier Lazarus         14
1080         François Meteyer         14
1082             Raffi Kamber         14
743         Rodolphe Menegaux         14
712          Guillaume Meulle         14
945            Fabrice Grinda         13
1068       Benjamin Wainstain         13
388           Cyril Vermeulen         13
1011          Eduardo Ronzano         13
596           Reza Malekzadeh         12
1074        Frédéric Mazzella         12
1660           Nicolas Boulay         12
546          Philippe Peltier         12
261            Francis Nappez         12
687             Thierry Petit         11
855       Bertrand Distinguin         11
847            Bruno Guicheux         11
299            Alexis Bonillo         11
2349          Michael Benabou         11
316              Didier Valet         11
1506         Oleg Tscheltzoff         11
722            Cyril Bertrand         11
570    Pierre-Yves Meerschman         11
482            Herve Cuviliez         11
1618            Leila Nicolas         11
116             Julien Creuze         11
841              Pauline Roux         10

In [141]:
# Drop rows where 'partners' column is NaN
df = df.dropna(subset=['Lead Partner'])

# Verify the result
df.head()

,Deal ID,Company ID,Company Name,Description,Investor ID,Investor Name,Investor Website,Investor Status,Primary Investor Type,Other Investor Types,...,Valuation/Cash Flow,Deal Status,Primary Industry Sector,Primary Industry Group,Primary Industry Code,Verticals,All Industries,Business Status,Financing Status,PitchBook Link
2,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,187980-13,Cathay Innovation,www.cathayinnovation.com,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
4,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,11180-08,Eurazeo,www.eurazeo.com,Active Investor,PE/Buyout,"Growth/Expansion, Infrastructure, Venture Capital",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
5,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,51189-94,HV Capital,www.hvcapital.com,Active Investor,Venture Capital,Growth/Expansion,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
30,272893-60T,530537-68,Wavo (Financial Software),Developer of a financial platform designed to ...,434507-50,Tony Parker,NaN,Active Investor,Angel (individual),NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Artificial Intelligence & Machine Learning, Fi...",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
32,285052-87T,512410-51,Smile Wanted Group,Operator of a digital advertising marketplace ...,58004-02,Bpifrance,www.bpifrance.fr,Active Investor,Sovereign Wealth Fund,"Accelerator/Incubator, Fund of Funds, Growth/E...",...,NaN,Completed,Business Products and Services (B2B),Commercial Services,Media and Information Services (B2B),"AdTech, Marketing Tech",Media and Information Services (B2B)*; Other C...,Generating Revenue,Venture Capital-Backed,NaN

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6436 entries, 2 to 21442
Data columns (total 62 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Deal ID                                     6436 non-null   object
 1   Company ID                                  6436 non-null   object
 2   Company Name                                6436 non-null   object
 3   Description                                 6436 non-null   object
 4   Investor ID                                 6436 non-null   object
 5   Investor Name                               6436 non-null   object
 6   Investor Website                            4040 non-null   object
 7   Investor Status                             6436 non-null   object
 8   Primary Investor Type                       6436 non-null   object
 9   Other Investor Types                        2677 non-null   object
 10  Preferred Industries                        5218 non-null   object
 11  Preferred Verticals                         4861 non-null   object
 12  Investor HQ                                 5416 non-null   object
 13  Investor AUM (million, USD)                 2957 non-null   float64
 14  Lead Partner                                6436 non-null   object
 15  Lead Partner Email                          3566 non-null   object
 16  Lead Partner Phone                          3221 non-null   object
 17  Lead/Sole                                   6436 non-null   object
 18  Fund(s) Used                                1781 non-null   object
 19  Deal No.                                    6436 non-null   int64
 20  Deal Date                                   6436 non-null   datetime64[ns]
 21  Total Deal Size (million, USD)              6200 non-null   float64
 22  Deal Size Status                            6200 non-null   object
 23  Investment Size (million, USD)              1321 non-null   float64
 24  Deal Type 1                                 6436 non-null   object
 25  Deal Type 2                                 2918 non-null   object
 26  Deal Type 3                                 0 non-null      float64
 27  Deal Class                                  6436 non-null   object
 28  Debts                                       1699 non-null   object
 29  Company City                                6396 non-null   object
 30  Company State/Province                      29 non-null     object
 31  Company Post Code                           6375 non-null   object
 32  Company Country/Territory                   6436 non-null   object
 33  Company Pre-money Valuation (million, USD)  4320 non-null   float64
 34  Company Post Valuation (million, USD)       4347 non-null   float64
 35  Company Post Valuation Status               4347 non-null   object
 36  Revenue (million, USD)                      1275 non-null   float64
 37  Revenue Status                              1250 non-null   object
 38  Revenue Growth since last deal              590 non-null    float64
 39  Gross Profit (million, USD)                 65 non-null     float64
 40  Gross Profit Status                         65 non-null     object
 41  Net Income (million, USD)                   881 non-null    float64
 42  Net Income Status                           881 non-null    object
 43  EBITDA (million, USD)                       719 non-null    float64
 44  EBITDA Status                               719 non-null    object
 45  Debt/Equity                                 515 non-null    float64
 46  Debt/EBITDA                                 223 non-null    float64
 47  Deal Size/EBITDA                            700 non-null    float64
 48  Valuation/EBITDA                            530 non-null    float64
 49  Deal Size/Revenue                           1225 non-null   float64
 50  Valuation/Revenue                           910 non-null    float64
 51  Deal Size/Cash Flow                         43 non-null     float64
 52  Valuation/Cash Flow                         32 non-null     float64
 53  Deal Status                                 6436 non-null   object
 54  Primary Industry Sector                     6436 non-null   object
 55  Primary Industry Group                      6436 non-null   object
 56  Primary Industry Code                       6436 non-null   object
 57  Verticals                                   6021 non-null   object
 58  All Industries                              6436 non-null   object
 59  Business Status                             6436 non-null   object
 60  Financing Status                            6433 non-null   object
 61  PitchBook Link                              0 non-null      float64
dtypes: datetime64[ns](1), float64(20), int64(1), object(40)
memory usage: 3.1+ MB

In [143]:
def most_relevant_sector_per_investor(df):
    # Group by investor and sector, count investments
    sector_counts = df.groupby(['Lead Partner', 'Primary Industry Sector']).size().reset_index(name='Investment Count')

    # Sort by investor and investment count (descending), then keep the top sector for each investor
    top_sectors = sector_counts.sort_values(['Lead Partner', 'Investment Count'], ascending=[True, False])
    
    most_relevant = top_sectors.drop_duplicates(subset='Lead Partner', keep='first')

    
    print(f"Dimensions of the resulting DataFrame: {most_relevant.shape}")
    print(f"Dimensions of the original DataFrame: {df.shape}")
    
    return most_relevant.reset_index(drop=True)

In [144]:
def most_relevant_sector_per_investor_search(df, name):
    # Group by investor and sector, count investments
    sector_counts = df.groupby(['Lead Partner', 'Primary Industry Sector']).size().reset_index(name='Investment Count')

    # Sort by investor and investment count (descending), then keep the top sector for each investor
    top_sectors = sector_counts.sort_values(['Lead Partner', 'Investment Count'], ascending=[True, False])
    
    top_sectors = top_sectors[top_sectors['Lead Partner'] == name]

    return top_sectors

In [145]:
# Apply the function to the dataset
relevant_sectors = most_relevant_sector_per_investor(df)

Dimensions of the resulting DataFrame: (3357, 3)
Dimensions of the original DataFrame: (6436, 62)

In [146]:
relevant_sectors.shape

(3357, 3)

In [147]:
# First, create a mapping from investor to their most relevant sector
investor_sector_map = relevant_sectors.set_index('Lead Partner')['Primary Industry Sector'].to_dict()

# Add the new column to the original DataFrame
df['Primary Investor Sector'] = df['Lead Partner'].map(investor_sector_map)

In [148]:
df.shape

(6436, 63)

In [149]:
# Filter rows where Lead Partner is either Benoist Grossman or Julien-David Nitchel
filtered_df = df[df['Lead Partner'].isin(['Benoist Grossmann', 'Julien-David Nitlech'])]

# Display the filtered rows
filtered_df.shape

(15, 63)

In [150]:
# Filter the data only by VC and BA

# For this Benoist Grossman and Julien-David Nitchel were not appearing in the dataset as they were not in the list of investors

# df = df[df["Primary Investor Type"].isin(["Venture Capital","Angel (individual)"])]
# df.head()

In [151]:
# Save the results to a new csv file
df.to_csv('data.csv', index=False)

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6436 entries, 2 to 21442
Data columns (total 63 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Deal ID                                     6436 non-null   object
 1   Company ID                                  6436 non-null   object
 2   Company Name                                6436 non-null   object
 3   Description                                 6436 non-null   object
 4   Investor ID                                 6436 non-null   object
 5   Investor Name                               6436 non-null   object
 6   Investor Website                            4040 non-null   object
 7   Investor Status                             6436 non-null   object
 8   Primary Investor Type                       6436 non-null   object
 9   Other Investor Types                        2677 non-null   object
 10  Preferred Industries                        5218 non-null   object
 11  Preferred Verticals                         4861 non-null   object
 12  Investor HQ                                 5416 non-null   object
 13  Investor AUM (million, USD)                 2957 non-null   float64
 14  Lead Partner                                6436 non-null   object
 15  Lead Partner Email                          3566 non-null   object
 16  Lead Partner Phone                          3221 non-null   object
 17  Lead/Sole                                   6436 non-null   object
 18  Fund(s) Used                                1781 non-null   object
 19  Deal No.                                    6436 non-null   int64
 20  Deal Date                                   6436 non-null   datetime64[ns]
 21  Total Deal Size (million, USD)              6200 non-null   float64
 22  Deal Size Status                            6200 non-null   object
 23  Investment Size (million, USD)              1321 non-null   float64
 24  Deal Type 1                                 6436 non-null   object
 25  Deal Type 2                                 2918 non-null   object
 26  Deal Type 3                                 0 non-null      float64
 27  Deal Class                                  6436 non-null   object
 28  Debts                                       1699 non-null   object
 29  Company City                                6396 non-null   object
 30  Company State/Province                      29 non-null     object
 31  Company Post Code                           6375 non-null   object
 32  Company Country/Territory                   6436 non-null   object
 33  Company Pre-money Valuation (million, USD)  4320 non-null   float64
 34  Company Post Valuation (million, USD)       4347 non-null   float64
 35  Company Post Valuation Status               4347 non-null   object
 36  Revenue (million, USD)                      1275 non-null   float64
 37  Revenue Status                              1250 non-null   object
 38  Revenue Growth since last deal              590 non-null    float64
 39  Gross Profit (million, USD)                 65 non-null     float64
 40  Gross Profit Status                         65 non-null     object
 41  Net Income (million, USD)                   881 non-null    float64
 42  Net Income Status                           881 non-null    object
 43  EBITDA (million, USD)                       719 non-null    float64
 44  EBITDA Status                               719 non-null    object
 45  Debt/Equity                                 515 non-null    float64
 46  Debt/EBITDA                                 223 non-null    float64
 47  Deal Size/EBITDA                            700 non-null    float64
 48  Valuation/EBITDA                            530 non-null    float64
 49  Deal Size/Revenue                           1225 non-null   float64
 50  Valuation/Revenue                           910 non-null    float64
 51  Deal Size/Cash Flow                         43 non-null     float64
 52  Valuation/Cash Flow                         32 non-null     float64
 53  Deal Status                                 6436 non-null   object
 54  Primary Industry Sector                     6436 non-null   object
 55  Primary Industry Group                      6436 non-null   object
 56  Primary Industry Code                       6436 non-null   object
 57  Verticals                                   6021 non-null   object
 58  All Industries                              6436 non-null   object
 59  Business Status                             6436 non-null   object
 60  Financing Status                            6433 non-null   object
 61  PitchBook Link                              0 non-null      float64
 62  Primary Investor Sector                     6436 non-null   object
dtypes: datetime64[ns](1), float64(20), int64(1), object(41)
memory usage: 3.1+ MB

In [153]:
# Calculate the threshold for 80% null values
threshold = len(df) * 0.8

# Drop columns with more than 80% null values
df = df.dropna(thresh=threshold, axis=1)

df.head()

,Deal ID,Company ID,Company Name,Description,Investor ID,Investor Name,Investor Status,Primary Investor Type,Preferred Industries,Investor HQ,...,Company Country/Territory,Deal Status,Primary Industry Sector,Primary Industry Group,Primary Industry Code,Verticals,All Industries,Business Status,Financing Status,Primary Investor Sector
2,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,187980-13,Cathay Innovation,Active Investor,Venture Capital,"Commercial Transportation, Healthcare Devices ...","San Francisco, CA",...,France,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,Information Technology
4,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,11180-08,Eurazeo,Active Investor,PE/Buyout,"Commercial Services, Consumer Non-Durables, En...","Paris, France",...,France,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,Information Technology
5,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,51189-94,HV Capital,Active Investor,Venture Capital,"Consumer Non-Durables, Education and Training ...","Munich, Germany",...,France,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,Information Technology
30,272893-60T,530537-68,Wavo (Financial Software),Developer of a financial platform designed to ...,434507-50,Tony Parker,Active Investor,Angel (individual),NaN,NaN,...,France,Completed,Information Technology,Software,Financial Software,"Artificial Intelligence & Machine Learning, Fi...",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,Consumer Products and Services (B2C)
32,285052-87T,512410-51,Smile Wanted Group,Operator of a digital advertising marketplace ...,58004-02,Bpifrance,Active Investor,Sovereign Wealth Fund,"Apparel and Accessories, Commercial Products, ...","Paris, France",...,France,Completed,Business Products and Services (B2B),Commercial Services,Media and Information Services (B2B),"AdTech, Marketing Tech",Media and Information Services (B2B)*; Other C...,Generating Revenue,Venture Capital-Backed,Business Products and Services (B2B)

In [154]:
df['Deal Date'] = pd.to_datetime(df['Deal Date'])
min_date = df['Deal Date'].min()
min_date

Timestamp('2010-01-01 00:00:00')

In [155]:
# Save the cleaned data to a new CSV file
df.to_csv('cleaned_data.csv', index=False)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6436 entries, 2 to 21442
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Deal ID                         6436 non-null   object
 1   Company ID                      6436 non-null   object
 2   Company Name                    6436 non-null   object
 3   Description                     6436 non-null   object
 4   Investor ID                     6436 non-null   object
 5   Investor Name                   6436 non-null   object
 6   Investor Status                 6436 non-null   object
 7   Primary Investor Type           6436 non-null   object
 8   Preferred Industries            5218 non-null   object
 9   Investor HQ                     5416 non-null   object
 10  Lead Partner                    6436 non-null   object
 11  Lead/Sole                       6436 non-null   object
 12  Deal No.                        6436 non-null   int64
 13  Deal Date                       6436 non-null   datetime64[ns]
 14  Total Deal Size (million, USD)  6200 non-null   float64
 15  Deal Size Status                6200 non-null   object
 16  Deal Type 1                     6436 non-null   object
 17  Deal Class                      6436 non-null   object
 18  Company City                    6396 non-null   object
 19  Company Post Code               6375 non-null   object
 20  Company Country/Territory       6436 non-null   object
 21  Deal Status                     6436 non-null   object
 22  Primary Industry Sector         6436 non-null   object
 23  Primary Industry Group          6436 non-null   object
 24  Primary Industry Code           6436 non-null   object
 25  Verticals                       6021 non-null   object
 26  All Industries                  6436 non-null   object
 27  Business Status                 6436 non-null   object
 28  Financing Status                6433 non-null   object
 29  Primary Investor Sector         6436 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(27)
memory usage: 1.5+ MB